---
kind: pipeline
name: "Verify & build app"

concurrency:
  limit: 2

steps:
  - name: Install everything
    image: node:16.13.1
    commands:
      - npm install react-scripts@latest
      - npm install @supabase/supabase-js
      - npm install @supabase/ui
      - npm run build

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: registry_username
    password: 
      from_secret: registry/password
    repo: vovakrut/supabase
    tags: {DRONE_COMMIT:0:7}

trigger:
  branch:
  - main

# trigger:
#   branch:
#     include:
#       - feature/*
#     exclude:
#       - main
